import {useEffect,useState,useCallback} from 'react';import {sb} from './supabase';
const ROLE_TABS={root:['Dashboard','Leads','Inbox Bot','Visitas','Instalaciones','Mantenimiento','Operaciones','Inventario','Usuarios','Auditoría'],sales:['Dashboard','Leads','Inbox Bot'],operations:['Visitas','Instalaciones','Mantenimiento','Inventario'],administrative:['Dashboard','Leads','Inbox Bot','Visitas','Instalaciones','Mantenimiento','Operaciones','Inventario']};
const ROLE_LABELS={root:'Root',sales:'Ventas',operations:'Operaciones',administrative:'Administrativo'};
const ASSIGNABLE_ROLES=[['','Pendiente · sin acceso'],['sales','Ventas'],['operations','Operaciones'],['administrative','Administrativo'],['root','Root']];
const STAT=['nuevo','contactado','visita','visitado','cerrado','rescatar','no'];
const PLAZAS=['Cuernavaca','Chihuahua','Playa del Carmen','Mérida'];
const PER=[['Histórico',0],['Hoy',1],['7 días',7],['30 días',30]];
const wa=n=>'https://wa.me/52'+String(n||'').replace(/\D/g,'').slice(-10);
const inPer=(x,d)=>!d||new Date(x.created_at)>=new Date(Date.now()-d*864e5);
const Filt=({plaza,setPlaza,per,setPer})=><div className="filter-controls"><select value={plaza} onChange={e=>setPlaza(e.target.value)} aria-label="Filtrar por plaza"><option value="">Todas las plazas</option>{PLAZAS.map(p=><option key={p}>{p}</option>)}</select><select value={per} onChange={e=>setPer(+e.target.value)} aria-label="Filtrar por periodo">{PER.map(([n,d])=><option key={n} value={d}>{n}</option>)}</select></div>;
const Bars=({rows})=>{const m=Math.max(1,...rows.map(r=>r[1]));return rows.map(([k,v])=><div key={k} style={{marginTop:10}}><div className="row" style={{margin:0,justifyContent:'space-between'}}><span className="mut">{k}</span><b>{v}</b></div><div className="bar"><i style={{width:v/m*100+'%'}}/></div></div>)};
const tally=(l,f)=>Object.entries(l.reduce((a,x)=>{const k=f(x)||'Sin dato';a[k]=(a[k]||0)+1;return a},{})).sort((a,b)=>b[1]-a[1]);
const money=n=>'$'+Number(n||0).toLocaleString('es-MX');
const useRows=(t,order='created_at')=>{const[r,setR]=useState([]);const[state,setState]=useState({loading:true,error:''});const load=useCallback(async()=>{setState({loading:true,error:''});try{const{data,error}=await sb.from(t).select('*').order(order,{ascending:false});if(error)throw error;setR(data||[]);setState({loading:false,error:''})}catch(error){setState({loading:false,error:error.message||'No se pudieron cargar los datos.'})}},[t,order]);useEffect(()=>{load()},[load]);return[r,load,state]};

function BrandMark(){return <svg className="auth-mark" viewBox="0 0 64 64" aria-hidden="true"><path d="M17 21h30l9 11H8l9-11Z" fill="currentColor"/><path d="M18 32h12v12h8V32h12v26H38v-9H30v9H18V32Z" fill="#0872ba"/><path d="M25 18V8m7 10V4m7 14 6-7m-20 7-6-7" fill="none" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/></svg>}

function ThemeToggle({theme,onChange}){return <div className="theme-toggle" aria-label="Tema"><button type="button" className={theme==='light'?'selected':''} aria-label="Tema claro" title="Tema claro" onClick={()=>onChange('light')}>☼</button><button type="button" className={theme==='dark'?'selected':''} aria-label="Tema oscuro" title="Tema oscuro" onClick={()=>onChange('dark')}>☾</button></div>}

function Login({theme,onThemeChange}){const[mode,setMode]=useState('login');const[name,setName]=useState('');const[area,setArea]=useState('');const[email,setEmail]=useState('');const[password,setPassword]=useState('');const[message,setMessage]=useState('');const[busy,setBusy]=useState(false);
 const requesting=mode==='request';
 const submit=async event=>{event.preventDefault();setMessage('');setBusy(true);
  if(requesting){const{data,error}=await sb.auth.signUp({email,password,options:{data:{full_name:name.trim(),area:area.trim()||null}}});
   if(error)setMessage(error.message);else setMessage(data.session?'Solicitud enviada. Tu cuenta quedará pendiente de aprobación.':'Solicitud recibida. Revisa tu correo para confirmar la cuenta; después quedará pendiente de aprobación.');
  }else{const{error}=await sb.auth.signInWithPassword({email,password});if(error)setMessage(error.message)}
  setBusy(false);
 };
 return <main className="auth-screen"><ThemeToggle theme={theme} onChange={onThemeChange}/><section className="auth-panel">
  <div className="auth-heading"><BrandMark/><h1>{requesting?'SOLICITAR ACCESO':'ACCESO SEGURO'}</h1><p>PANEL DE CONTROL THERMO HOUSE</p></div>
  <form className="auth-form" onSubmit={submit}>
   {requesting&&<><label htmlFor="auth-name">Nombre completo</label><input id="auth-name" autoComplete="name" value={name} onChange={event=>setName(event.target.value)} required/></>}
   <label htmlFor="auth-email">Correo electrónico</label><input id="auth-email" type="email" autoComplete="email" value={email} onChange={event=>setEmail(event.target.value)} required/>
   <label htmlFor="auth-password">Contraseña</label><input id="auth-password" type="password" autoComplete={requesting?'new-password':'current-password'} minLength={requesting?6:undefined} value={password} onChange={event=>setPassword(event.target.value)} required/>
   {requesting&&<><label htmlFor="auth-area">Área o puesto <span>(opcional)</span></label><input id="auth-area" placeholder="Ej. Ventas, Instalaciones" value={area} onChange={event=>setArea(event.target.value)}/></>}
   <button className="auth-submit" type="submit" disabled={busy}>{busy?'PROCESANDO…':requesting?'SOLICITAR ACCESO':'ENTRAR AL DASHBOARD'} <span aria-hidden="true">{requesting?'↗':'♢'}</span></button>
  </form>
  {message&&<p className="auth-message" role="status">{message}</p>}
  <p className="auth-switch">{requesting?'¿Ya tienes cuenta?':'¿Aún no tienes cuenta?'} <button type="button" onClick={()=>{setMode(requesting?'login':'request');setMessage('')}}>{requesting?'Inicia sesión':'Solicita acceso'}</button></p>
  <footer className="auth-footer">SISTEMA DE SEGURIDAD THERMO HOUSE © {new Date().getFullYear()}</footer>
 </section></main>}

function AccessStatus({error,onSignOut,legacy=false}){return <main className="auth-screen"><section className="auth-panel auth-status"><BrandMark/><h1>{error?'NO SE PUDO VALIDAR TU ACCESO':legacy?'DEPARTAMENTO POR ASIGNAR':'SOLICITUD PENDIENTE'}</h1><p>{error?'Ocurrió un problema al consultar tu autorización. Intenta de nuevo más tarde.':legacy?'Tu cuenta conserva el acceso anterior, pero necesita que root le asigne Ventas, Operaciones o Administrativo para continuar.':'Un administrador debe asignarte un departamento antes de habilitar el acceso.'}</p><button className="auth-submit" onClick={onSignOut}>CERRAR SESIÓN</button></section></main>}

function Dashboard(){const[all,,loadState]=useRows('leads');const[plaza,setPlaza]=useState('');const[per,setPer]=useState(0);
 const l=all.filter(x=>inPer(x,per)&&(!plaza||(x.ciudad||'').includes(plaza)));const n=l.length||1;const c=s=>l.filter(x=>x.status===s).length;
 const cerr=c('cerrado'),sin=l.filter(x=>x.status==='nuevo'),pag=tally(l.filter(x=>x.tipo_precio),x=>x.tipo_precio==='efectivo'?'Contado':'12 MSI'),ases=[...new Set(l.map(x=>x.asesor).filter(Boolean))];
 const P=[['rescatar','Por rescatar'],['nuevo','Nuevo'],['contactado','Contactado'],['visita','Visita técnica'],['cerrado','Cerrado']];
 if(loadState.loading&&!all.length)return <div className="panel-feedback">Cargando dashboard…</div>;
 if(loadState.error&&!all.length)return <div className="panel-feedback error" role="alert">No se pudieron cargar los leads: {loadState.error}</div>;
 return <><div className="dashboard-toolbar"><h2>Dashboard general</h2><Filt {...{plaza,setPlaza,per,setPer}}/></div>{loadState.error&&<p className="data-alert" role="alert">No se pudieron actualizar los datos: {loadState.error}</p>}
 <div className="grid">{P.map(([s,t])=><div className="card" key={s}><span className="lbl">{t}</span><div className={'big '+(s==='cerrado'?'or':'')}>{c(s)}</div><span className="mut">{Math.round(c(s)/n*100)}% del total</span><div className="bar"><i style={{width:c(s)/n*100+'%'}}/></div></div>)}</div>
 <div className="grid">{[['Total leads',l.length],['Ventas cerradas',cerr],['Tasa de conversión',(l.length?Math.round(cerr/l.length*100):0)+'%'],['Sin atender',sin.length]].map(([t,v])=><div className="card" key={t}><span className="lbl">{t}</span><div className="big or">{v}</div></div>)}</div>
 <div className="grid"><div className="card"><h3><span className="ico">📊</span>Sistemas más solicitados</h3><Bars rows={tally(l,x=>x.sistema)}/></div>
 <div className="card"><h3><span className="ico">💳</span>Preferencias de pago</h3><Bars rows={pag}/></div>
 <div className="card"><h3><span className="ico">📍</span>Por ciudad</h3><table><tbody>{tally(l,x=>(x.ciudad||'').split(',')[0].trim()).slice(0,8).map(([k,v])=><tr key={k}><td>{k}</td><td><b>{v}</b></td></tr>)}</tbody></table></div></div>
 <div className="card" style={{marginBottom:16}}><h3><span className="ico">🔔</span>Atención prioritaria</h3>{sin.slice(0,6).map(x=><div key={x.id} className="row"><span className="av">{(x.nombre||'?')[0]}</span><span style={{flex:1}}>{x.nombre}</span><span className="pill nuevo">sin atender</span></div>)}{!sin.length&&<p className="mut">Todo atendido.</p>}</div>
 <div className="grid">{ases.map(a=>{const m=l.filter(x=>x.asesor===a);const k=s=>m.filter(x=>x.status===s).length;return <div className="card" key={a}><span className="lbl">{a}</span><div className="mut" style={{margin:'8px 0'}}>Nuevos {k('nuevo')} · Contactados {k('contactado')} · Visita {k('visita')} · Cerrados {k('cerrado')}</div><div className="big or">{Math.round(k('cerrado')/(m.length||1)*100)}%</div><span className="mut">% de cierre</span></div>})}</div></>}

function Quote({onClose,onSaved,init}){const[f,setF]=useState({nombre:'',whatsapp:'',email:'',origen:'',ciudad:'Cuernavaca',cp:'',direccion:'',area_m2:0,tipo_precio:'efectivo',sistema:'TH FIX',costo_logistico:0,notas:'',voltaje:'',canal_venta:'',presentacion:'',fecha_contacto:'',...Object.fromEntries(Object.entries(init||{}).map(([k,v])=>[k,v??'']))});const[t,setT]=useState([]);const[tariffState,setTariffState]=useState({loading:true,error:''});const[busy,setBusy]=useState(false);const[saveError,setSaveError]=useState('');
 useEffect(()=>{let active=true;setTariffState({loading:true,error:''});sb.from('tarifas').select('*').eq('ciudad',f.ciudad).then(({data,error})=>{if(!active)return;setT(data||[]);setTariffState({loading:false,error:error?.message||(!data?.length?`No hay tarifas configuradas para ${f.ciudad}.`:'')})});return()=>{active=false}},[f.ciudad]);
 const s=k=>e=>setF({...f,[k]:e.target.value});const tar=t.find(x=>x.producto_id===f.sistema);
 const unit=tar?(f.tipo_precio==='efectivo'?tar.precio_contado:tar.precio_msi):0;
 const sub=f.area_m2>0?Math.max(unit*f.area_m2,tar?.minimo||0):0;const total=sub+Number(f.costo_logistico||0);
 const save=async()=>{setSaveError('');setBusy(true);try{if(!f.nombre.trim())throw new Error('El nombre del cliente es obligatorio.');if(!init&&Number(f.area_m2)>0&&!tar)throw new Error(tariffState.error||'No se encontró una tarifa para la ciudad y sistema seleccionados.');const{data:{user},error:userError}=await sb.auth.getUser();if(userError)throw userError;if(!user)throw new Error('La sesión expiró. Inicia sesión de nuevo.');const{id,created_at,...rest}=f;const row={...rest,area_m2:+f.area_m2||0,costo_logistico:+f.costo_logistico||0,total:tar?total:Number(init?.total||0),fecha_contacto:f.fecha_contacto||null,fecha_kam:f.fecha_kam||null,fecha_nacimiento:f.fecha_nacimiento||null};const result=init?.id?await sb.from('leads').update(row).eq('id',init.id):await sb.from('leads').insert({...row,asesor:user.email,folio:'QT-'+Date.now().toString().slice(-4)});if(result.error)throw result.error;await onSaved();onClose()}catch(error){setSaveError(error.message||'No se pudo guardar la cotización.')}finally{setBusy(false)}};
 return <div className="modal"><div className="card"><div className="row"><h3 style={{flex:1}}>Nueva cotización manual</h3><button className="btn ghost" onClick={onClose}>✕</button></div>
 <div className="f"><div><label>Nombre</label><input value={f.nombre} onChange={s('nombre')}/></div><div><label>WhatsApp</label><input value={f.whatsapp} onChange={s('whatsapp')}/></div>
 <div><label>Correo</label><input value={f.email} onChange={s('email')}/></div><div><label>Origen</label><select value={f.origen} onChange={s('origen')}><option value="">Seleccione…</option>{['WhatsApp','Facebook','Referido','Otro'].map(o=><option key={o}>{o}</option>)}</select></div>
 <div><label>Código postal</label><input value={f.cp} onChange={s('cp')}/></div><div><label>Zona de presupuesto</label><input value={f.ciudad} onChange={s('ciudad')}/></div>
 <div className="w"><label>Dirección exacta</label><input value={f.direccion} onChange={s('direccion')}/></div>
 <div><label>Área verificada (m²)</label><input type="number" value={f.area_m2} onChange={s('area_m2')}/></div>
 <div><label>Tipo de precio</label><select value={f.tipo_precio} onChange={s('tipo_precio')}><option value="efectivo">Efectivo</option><option value="msi">Lista/Promoción (MSI)</option></select></div>
 <div><label>Sistema</label><select value={f.sistema} onChange={s('sistema')}><option value="">—</option>{t.map(x=><option key={x.id} value={x.producto_id}>{x.producto_id}</option>)}</select></div>
 <div><label>Costo logístico (foráneo)</label><input type="number" value={f.costo_logistico} onChange={s('costo_logistico')}/></div>
 <div><label>Voltaje</label><input value={f.voltaje} onChange={s('voltaje')}/></div><div><label>Canal de venta</label><select value={f.canal_venta} onChange={s('canal_venta')}><option value="">—</option><option>Servicio al Cliente</option><option>KAM</option></select></div><div><label>Presentación contratada</label><input value={f.presentacion} onChange={s('presentacion')}/></div><div><label>Fecha de contacto</label><input type="date" value={f.fecha_contacto} onChange={s('fecha_contacto')}/></div>
 <div className="w"><label>Notas internas</label><textarea value={f.notas} onChange={s('notas')}/></div></div>
 {tariffState.error&&Number(f.area_m2)>0&&<p className="data-alert" role="alert">{tariffState.error}</p>}{saveError&&<p className="data-alert" role="alert">{saveError}</p>}<p className="big">Total estimado: {money(total)}</p><button type="button" className="btn" onClick={save} disabled={!f.nombre.trim()||busy||(!init&&Number(f.area_m2)>0&&(tariffState.loading||!tar))}>{busy?'Guardando…':'Guardar cotización'}</button></div></div>}

function Report({l,onClose}){return <div className="modal"><div className="card" style={{background:'#fff',color:'#000'}}><div className="print" style={{background:'#fff',color:'#000'}}>
 <h2 style={{color:'#ff7a1a'}}>THERMO HOUSE · Cotización {l.folio}</h2><p>{[l.nombre,l.whatsapp&&'+52 '+l.whatsapp].filter(Boolean).join(' · ')}<br/>{[l.direccion,l.ciudad].filter(Boolean).join(', ')}</p>
 <table><tbody><tr><td>{l.sistema} ({l.tipo_precio})</td><td>{l.area_m2} m²</td><td>{money(l.total)}</td></tr></tbody></table>
 <p>Precios en pesos mexicanos. Válidos 7 días hábiles. Atendido por: {l.asesor}</p></div>
 <div className="row"><button className="btn" onClick={()=>window.print()}>Generar PDF</button><button className="btn ghost" onClick={onClose}>Cerrar</button></div></div></div>}

function Leads({readOnly=false}){const[l,load,loadState]=useRows('leads');const[q,setQ]=useState('');const[fs,setFs]=useState('');const[m,setM]=useState(false);const[rep,setRep]=useState(null);const[ed,setEd]=useState(null);const[plaza,setPlaza]=useState('');const[per,setPer]=useState(0);const[actionError,setActionError]=useState('');const[busyId,setBusyId]=useState(null);
 const rows=l.filter(x=>(!fs||x.status===fs)&&inPer(x,per)&&(!plaza||(x.ciudad||'').includes(plaza))&&((x.nombre||'')+(x.whatsapp||'')).toLowerCase().includes(q.toLowerCase()));
 const updateStatus=async(id,status)=>{setActionError('');setBusyId(id);try{const{error}=await sb.from('leads').update({status}).eq('id',id);if(error)throw error;await load()}catch(error){setActionError(error.message||'No se pudo actualizar el estado.')}finally{setBusyId(null)}};
 const deleteLead=async id=>{if(!confirm('¿Eliminar este lead?'))return;setActionError('');setBusyId(id);try{const{error}=await sb.from('leads').delete().eq('id',id);if(error)throw error;await load()}catch(error){setActionError(error.message||'No se pudo eliminar el lead.')}finally{setBusyId(null)}};
 return <><div className="lead-toolbar"><div className="lead-main-actions">{!readOnly&&<button className="btn" onClick={()=>setM(true)}>+ Nuevo cliente</button>}<input className="lead-search" type="search" aria-label="Buscar cliente" placeholder="Buscar por nombre o teléfono" value={q} onChange={e=>setQ(e.target.value)}/></div><Filt {...{plaza,setPlaza,per,setPer}}/><div className="status-filters" aria-label="Filtrar por estado">{['',...STAT].map(s=><button type="button" key={s||'todos'} aria-pressed={fs===s} className={'btn chip '+(fs===s?'':'ghost')} onClick={()=>setFs(s)}>{s||'Todos'}</button>)}</div></div>
 {actionError&&<p className="data-alert" role="alert">{actionError}</p>}{loadState.error&&<p className="data-alert" role="alert">No se pudieron actualizar los leads: {loadState.error}</p>}{loadState.loading&&!l.length&&<div className="panel-feedback">Cargando leads…</div>}
 <div className="card tbl lead-table"><table><thead><tr><th>Cliente</th><th>Ubicación</th><th>Cotización</th><th>Asesor</th><th>Status</th><th>Acciones</th></tr></thead><tbody>
 {rows.map(x=><tr key={x.id}><td><span className="av">{(x.nombre||'?').split(' ').map(w=>w[0]).slice(0,2).join('')}</span>{x.nombre}<div className="mut">{x.whatsapp||'Sin teléfono'} · {x.folio}</div></td><td>{x.ciudad}<div className="mut">{x.area_m2} m² · {x.sistema}</div></td><td>{money(x.total)}</td><td>{x.asesor||'Sin asignar'}</td>
 <td>{readOnly?<span className={'pill '+x.status}>{x.status}</span>:<select aria-label={'Estado de '+x.nombre} value={x.status} disabled={busyId===x.id} onChange={e=>updateStatus(x.id,e.target.value)}>{STAT.map(s=><option key={s}>{s}</option>)}</select>}</td>
 <td><div className="lead-row-actions">{x.whatsapp?<a className="btn ghost" href={wa(x.whatsapp)} target="_blank" rel="noreferrer">WhatsApp</a>:<span className="mut">Sin teléfono</span>}{!readOnly&&<button className="btn ghost" onClick={()=>setEd(x)}>Editar</button>}<button className="btn ghost" onClick={()=>setRep(x)}>PDF</button>{!readOnly&&<button className="btn red" disabled={busyId===x.id} onClick={()=>deleteLead(x.id)}>Eliminar</button>}</div></td></tr>)}</tbody></table>{!loadState.loading&&!loadState.error&&!rows.length&&<p className="mut">No hay leads que coincidan con estos filtros.</p>}</div>
 {m&&<Quote onClose={()=>setM(false)} onSaved={load}/>}{ed&&<Quote init={ed} onClose={()=>setEd(null)} onSaved={load}/>}{rep&&<Report l={rep} onClose={()=>setRep(null)}/>}</>}

function Crud({table,title,order,fields,extra,readOnly=false}){const[r,load,loadState]=useRows(table,order);const[ed,setEd]=useState(null);const[e,setE]=useState({});const[busy,setBusy]=useState(false);const[actionError,setActionError]=useState('');
 const open=x=>{setActionError('');setEd(x);setE(Object.fromEntries(fields.map(([k,,type])=>{const value=x[k]??'';return[k,type==='datetime-local'&&value?new Date(value).toISOString().slice(0,16):value]})))};
 const save=async()=>{setActionError('');setBusy(true);try{const row=Object.fromEntries(Object.entries(e).map(([k,v])=>[k,v===''?null:v]));const{error}=ed.id?await sb.from(table).update(row).eq('id',ed.id):await sb.from(table).insert(row);if(error)throw error;setEd(null);await load()}catch(error){setActionError(error.message||'No se pudo guardar el registro.')}finally{setBusy(false)}};
 const del=async()=>{if(!confirm('¿Eliminar registro?'))return;setActionError('');setBusy(true);try{const{error}=await sb.from(table).delete().eq('id',ed.id);if(error)throw error;setEd(null);await load()}catch(error){setActionError(error.message||'No se pudo eliminar el registro.')}finally{setBusy(false)}};
 const runExtra=async action=>{setActionError('');setBusy(true);try{await action();await load()}catch(error){setActionError(error.message||'No se pudo completar la acción.')}finally{setBusy(false)}};
 return <div className="card tbl"><div className="row"><h3 style={{flex:1}}>{title}</h3>{!readOnly&&<button type="button" className="btn" onClick={()=>{setActionError('');open({})}}>+ Agregar</button>}</div>
 {actionError&&<p className="data-alert" role="alert">{actionError}</p>}{loadState.error&&<p className="data-alert" role="alert">{loadState.error}</p>}{loadState.loading&&!r.length&&<p className="mut">Cargando registros…</p>}
 <table><thead><tr>{fields.map(f=><th key={f[0]}>{f[1]}</th>)}{!readOnly&&<th>Acciones</th>}</tr></thead><tbody>{r.map(x=><tr key={x.id}>{fields.map(f=><td key={f[0]}>{String(x[f[0]]??'')}</td>)}{!readOnly&&<td><button type="button" className="btn ghost" disabled={busy} onClick={()=>open(x)}>Editar</button> {extra?.(x,runExtra,busy)}</td>}</tr>)}</tbody></table>
 {!r.length&&!loadState.loading&&!loadState.error&&<p className="mut">Sin registros todavía. Usa "+ Agregar".</p>}
 {ed&&<div className="modal"><div className="card"><h3>{ed.id?'Editar':'Nuevo'} · {title}</h3><div className="f">{fields.map(([k,l,t,o])=><div key={k}><label>{l}</label>{t==='select'?<select value={e[k]} onChange={x=>setE({...e,[k]:x.target.value})}><option value="">—</option>{o.map(v=><option key={v}>{v}</option>)}</select>:<input type={t||'text'} value={e[k]} onChange={x=>setE({...e,[k]:x.target.value})}/>}</div>)}</div>
 {actionError&&<p className="data-alert" role="alert">{actionError}</p>}<div className="row" style={{marginTop:14}}><button type="button" className="btn" disabled={busy} onClick={save}>{busy?'Guardando…':'Guardar'}</button><button type="button" className="btn ghost" disabled={busy} onClick={()=>setEd(null)}>Cancelar</button>{ed.id&&<button type="button" className="btn ghost" disabled={busy} onClick={del}>Eliminar</button>}</div></div></div>}</div>}

function Precios({readOnly=false}){const[r,load,loadState]=useRows('tarifas','producto_id');const[saving,setSaving]=useState(null);const[message,setMessage]=useState('');const[messageIsError,setMessageIsError]=useState(false);
 const up=async(id,k,rawValue)=>{const value=Number(rawValue);if(rawValue.trim()===''||!Number.isFinite(value)||value<0){setMessage('Ingresa una cantidad válida, igual o mayor que cero.');setMessageIsError(true);return}setMessage('');setSaving(`${id}:${k}`);try{const{error}=await sb.from('tarifas').update({[k]:value}).eq('id',id);if(error)throw error;await load();setMessage('Tarifa guardada.');setMessageIsError(false)}catch(error){setMessage(error.message||'No se pudo guardar la tarifa.');setMessageIsError(true)}finally{setSaving(null)}};
 return <div className="card tbl"><h3>Lista de tarifas regionales</h3>{loadState.loading&&!r.length&&<p className="mut">Cargando tarifas…</p>}{loadState.error&&<p className="data-alert" role="alert">{loadState.error}</p>}{message&&<p className={messageIsError?'data-alert':'panel-feedback'} role={messageIsError?'alert':'status'}>{message}</p>}<table><thead><tr><th>Ciudad</th><th>Sistema</th><th>Contado /m²</th><th>MSI /m²</th><th>Mínimo</th></tr></thead><tbody>
 {r.map(x=><tr key={x.id}><td>{x.ciudad}</td><td>{x.producto_id}</td>{['precio_contado','precio_msi','minimo'].map(k=><td key={k}>{readOnly?money(x[k]):<input aria-label={`${x.ciudad} ${x.producto_id} ${k}`} type="number" min="0" step="0.01" style={{width:100}} defaultValue={x[k]} disabled={saving===`${x.id}:${k}`} onBlur={e=>up(x.id,k,e.target.value)}/>}</td>)}</tr>)}</tbody></table></div>}

function RootUsers({currentUserId}){const[users,load,state]=useRows('profiles','created_at');const[busy,setBusy]=useState(null);const[message,setMessage]=useState('');const[isError,setIsError]=useState(false);const ordered=[...users].sort((a,b)=>Number(Boolean(a.role))-Number(Boolean(b.role)));
 const assign=async(id,role)=>{setBusy(id);setMessage('');try{const{error}=await sb.from('profiles').update({role:role||null}).eq('id',id);if(error)throw error;await load();setMessage('Permisos actualizados.');setIsError(false)}catch(error){setMessage(error.message||'No se pudieron actualizar los permisos.');setIsError(true)}finally{setBusy(null)}};
 return <div className="card tbl"><div className="row"><h2 style={{flex:1}}>Usuarios y solicitudes</h2><span className="pill nuevo">{users.filter(user=>!user.role).length} pendientes</span></div><p className="mut">Solo root puede aprobar solicitudes y asignar departamentos.</p>{state.error&&<p className="data-alert" role="alert">{state.error}</p>}{message&&<p className={isError?'data-alert':'panel-feedback'} role={isError?'alert':'status'}>{message}</p>}{state.loading&&!users.length&&<p className="mut">Cargando usuarios…</p>}
 <table><thead><tr><th>Persona</th><th>Área</th><th>Solicitud</th><th>Departamento</th></tr></thead><tbody>{ordered.map(user=><tr key={user.id}><td><strong>{user.full_name||'Sin nombre'}</strong><div className="mut">{user.email||user.id}</div></td><td>{user.area||'Sin especificar'}</td><td>{new Date(user.created_at).toLocaleDateString('es-MX')}</td><td><select className="role-picker" aria-label={`Departamento de ${user.email||user.id}`} value={user.role||''} disabled={busy===user.id||user.id===currentUserId} onChange={event=>assign(user.id,event.target.value)}>{ASSIGNABLE_ROLES.map(([value,label])=><option key={value||'pending'} value={value}>{label}</option>)}</select></td></tr>)}</tbody></table>{!state.loading&&!state.error&&!users.length&&<p className="mut">No hay solicitudes ni usuarios.</p>}</div>}

function RootAudit(){const[events,,state]=useRows('security_events','occurred_at');return <div className="card tbl audit-table"><h2>Auditoría de actividad</h2><p className="mut">Cambios persistidos en datos y permisos. Los intentos de acceso fallidos se consultan en los registros de autenticación de Supabase.</p>{state.loading&&!events.length&&<p className="mut">Cargando actividad…</p>}{state.error&&<p className="data-alert" role="alert">{state.error}</p>}<table><thead><tr><th>Fecha</th><th>Usuario</th><th>Acción</th><th>Área</th><th>Registro</th></tr></thead><tbody>{events.map(event=><tr key={event.id}><td>{new Date(event.occurred_at).toLocaleString('es-MX')}</td><td>{event.actor_email||'Sistema / sin sesión'}</td><td>{event.action}</td><td>{event.entity_table}</td><td>{event.entity_id||'—'}</td></tr>)}</tbody></table>{!state.loading&&!state.error&&!events.length&&<p className="mut">Aún no hay actividad registrada.</p>}</div>}

export default function App(){const[s,setS]=useState(null);const[authReady,setAuthReady]=useState(false);const[profile,setProfile]=useState(null);const[profileLoading,setProfileLoading]=useState(false);const[profileError,setProfileError]=useState(false);const[tab,setTab]=useState('Dashboard');const[dk,setDk]=useState(()=>localStorage.getItem('th')||'dark');
 useEffect(()=>{document.documentElement.dataset.theme=dk;localStorage.setItem('th',dk)},[dk]);
 useEffect(()=>{sb.auth.getSession().then(({data})=>{setS(data.session);setAuthReady(true)});const{data:{subscription}}=sb.auth.onAuthStateChange((_,x)=>{setS(x);setAuthReady(true)});return()=>subscription.unsubscribe()},[]);
 useEffect(()=>{if(!s){setProfile(null);setProfileError(false);return}let active=true;setProfileLoading(true);sb.from('profiles').select('full_name,role').eq('id',s.user.id).single().then(({data,error})=>{if(active){setProfile(data);setProfileError(Boolean(error));setProfileLoading(false)}});return()=>{active=false}},[s?.user?.id]);
 if(!authReady)return <main className="auth-screen"><div className="auth-loading">THERMO HOUSE</div></main>;
 if(!s)return <Login theme={dk} onThemeChange={setDk}/>;
 if(profileLoading)return <main className="auth-screen"><div className="auth-loading">VALIDANDO ACCESO…</div></main>;
 if(profileError||!profile||!ROLE_TABS[profile.role])return <AccessStatus error={profileError} legacy={profile?.role==='member'} onSignOut={()=>sb.auth.signOut()}/>;
 const role=profile.role;const visibleTabs=ROLE_TABS[role]||[];const activeTab=visibleTabs.includes(tab)?tab:visibleTabs[0];const canManageOperations=role==='root'||role==='operations';const canManageAdministration=role==='root'||role==='administrative';
 const V={Dashboard:<Dashboard/>,Leads:<Leads readOnly={role==='administrative'}/>,
 'Inbox Bot':<Crud table="bot_inbox" title="Buzón bot" readOnly={role==='administrative'} extra={(x,run,busy)=>x.status!=='convertido'&&<button type="button" className="btn" disabled={busy} onClick={()=>run(async()=>{const{data:{user},error:userError}=await sb.auth.getUser();if(userError)throw userError;if(!user)throw new Error('La sesión expiró.');const{error:leadError}=await sb.from('leads').upsert({nombre:x.nombre,whatsapp:x.telefono,ciudad:x.ciudad,sistema:x.sistema,total:x.monto||0,origen:'Bot WhatsApp',notas:x.notas,asesor:user.email,folio:'BOT-'+x.id},{onConflict:'folio'});if(leadError)throw leadError;const{error:inboxError}=await sb.from('bot_inbox').update({status:'convertido'}).eq('id',x.id);if(inboxError)throw new Error('El lead se guardó, pero no se pudo marcar como convertido: '+inboxError.message)})}>Convertir</button>} fields={[['nombre','Nombre'],['telefono','Teléfono'],['ciudad','Ciudad'],['sistema','Sistema'],['monto','Monto','number'],['status','Status','select',['pendiente','contactado','convertido','descartado']],['notas','Notas']]}/>,
 Visitas:<Crud table="visitas" title="Visitas" readOnly={!canManageOperations} extra={canManageOperations?(x,run,busy)=>x.status==='por_visitar'&&<button type="button" className="btn" disabled={busy} onClick={()=>run(async()=>{const{error}=await sb.rpc('complete_visit',{visit_id:x.id});if(error)throw error})}>Marcar hecha</button>:undefined} order="programacion" fields={[['cliente','Cliente'],['ubicacion','Ubicación'],['programacion','Programación','datetime-local'],['status','Status','select',['por_visitar','realizada','cancelada']]]}/>,
 Instalaciones:<Crud table="obras" title="Obras" readOnly={!canManageOperations} order="programacion" fields={[['folio','Folio'],['cliente','Cliente'],['programacion','Programación','date'],['direccion','Dirección'],['m2','m²','number'],['status','Status','select',['por_iniciar','en_proceso','entregada']]]}/>,
 Mantenimiento:<Crud table="garantias" title="Gestión de garantías" readOnly={!canManageOperations} order="proximo_mtto" fields={[['cliente','Cliente'],['folio','Folio'],['sistema','Sistema'],['instalacion','Instalación','date'],['proximo_mtto','Próximo mtto.','date'],['status','Status','select',['activa','vencida','mantenimiento_hecho']]]}/>,
 Operaciones:<Precios readOnly={!canManageAdministration}/>,
 Inventario:<Crud table="barriles" title="Control de inventario · barriles" readOnly={!canManageOperations&&!canManageAdministration} order="entrada" fields={[['plaza','Plaza','select',['Cuernavaca','Chihuahua','Playa del Carmen','Mérida']],['tipo','Tipo','select',['isocianato','poliol']],['lote','Lote'],['estado','Estado','select',['cerrado','abierto','vacío']],['entrada','Entrada','date']]}/>,
 Usuarios:<RootUsers currentUserId={s.user.id}/>,
 Auditoría:<RootAudit/>};
 return <><header className="app-header"><div className="brand"><span className="logo">N</span><div className="brand-copy"><h1>NEXUS <b>ADMIN</b> <span className="mut">V1.1</span></h1><div className="brand-meta"><span className="badge">{ROLE_LABELS[role]}</span><span className="mut">{s.user?.email}</span></div></div></div><nav className="app-nav" aria-label="Navegación principal">{visibleTabs.map(t=><button key={t} className={t===activeTab?'on':''} aria-current={t===activeTab?'page':undefined} onClick={()=>setTab(t)}>{t}</button>)}</nav><div className="app-actions"><button className="btn ghost" onClick={()=>setDk(dk==='dark'?'light':'dark')}>{dk==='dark'?'☀ Claro':'☾ Oscuro'}</button><button className="btn red" onClick={()=>sb.auth.signOut()}>Salir</button></div></header><main>{V[activeTab]}</main></>}
